// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwK6RWu01W_ZwPtIEA4wvjqyQxNW6sTiA',
    appId: '1:487718155663:web:d89a7310cf5cc2dcf007fa',
    messagingSenderId: '487718155663',
    projectId: 'finpilot-d17ee',
    authDomain: 'finpilot-d17ee.firebaseapp.com',
    storageBucket: 'finpilot-d17ee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI5aXm_55sSfcywtaq6mCLomaoXoxhT1s',
    appId: '1:487718155663:android:2074b285e6d2f388f007fa',
    messagingSenderId: '487718155663',
    projectId: 'finpilot-d17ee',
    storageBucket: 'finpilot-d17ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAbpba_9ua-mBb1DchLXA4FMZeKb7wQmc',
    appId: '1:487718155663:ios:199d01d6062f445ef007fa',
    messagingSenderId: '487718155663',
    projectId: 'finpilot-d17ee',
    storageBucket: 'finpilot-d17ee.firebasestorage.app',
    iosBundleId: 'com.example.finpilot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAbpba_9ua-mBb1DchLXA4FMZeKb7wQmc',
    appId: '1:487718155663:ios:199d01d6062f445ef007fa',
    messagingSenderId: '487718155663',
    projectId: 'finpilot-d17ee',
    storageBucket: 'finpilot-d17ee.firebasestorage.app',
    iosBundleId: 'com.example.finpilot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwK6RWu01W_ZwPtIEA4wvjqyQxNW6sTiA',
    appId: '1:487718155663:web:c0da91151652bc41f007fa',
    messagingSenderId: '487718155663',
    projectId: 'finpilot-d17ee',
    authDomain: 'finpilot-d17ee.firebaseapp.com',
    storageBucket: 'finpilot-d17ee.firebasestorage.app',
  );
}
